/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#474747',
        'surface-container-low': '#1b1c1c',
        'inverse-on-surface': '#303030',
        'secondary': '#c5c7c8',
        'primary-fixed': '#e2e2e2',
        'on-primary': '#303030',
        'surface-bright': '#393939',
        'on-secondary': '#2e3132',
        'on-surface': '#e4e2e1',
        'secondary-fixed-dim': '#c5c7c8',
        'inverse-surface': '#e4e2e1',
        'secondary-fixed': '#e1e3e4',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#454748',
        'tertiary-container': '#000000',
        'tertiary-fixed-dim': '#c6c6c6',
        'surface-container': '#1f2020',
        'surface': '#131313',
        'surface-container-high': '#2a2a2a',
        'primary': '#c6c6c6',
        'surface-variant': '#353535',
        'outline': '#988e90',
        'on-background': '#e4e2e1',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#1b1b1b',
        'error-container': '#93000a',
        'primary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#191c1d',
        'on-primary-fixed': '#1b1b1b',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary': '#303030',
        'background': '#131313',
        'primary-container': '#000000',
        'outline-variant': '#4c4546',
        'on-primary-fixed-variant': '#474747',
        'inverse-primary': '#5e5e5e',
        'on-tertiary-container': '#757575',
        'surface-dim': '#131313',
        'on-secondary-container': '#babcbd',
        'tertiary-fixed': '#e2e2e2',
        'secondary-container': '#494c4d',
        'surface-tint': '#c6c6c6',
        'surface-container-highest': '#353535',
        'on-surface-variant': '#cfc4c5',
        'on-primary-container': '#757575',
        'tertiary': '#c6c6c6',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'container-max': '1200px',
        'margin-md': '32px',
        'margin-sm': '16px',
        'element-gap': '24px',
        'section-gap': '128px',
        'margin-lg': '64px',
        'gutter': '24px',
      },
      fontFamily: {
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-xl': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'headline-xl-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

